
import type { Exam, Subject, QuizDifficultyLevel } from '@/types';

export const EXAM_TYPES: Exam[] = [
  { value: 'jee', label: 'JEE (Main & Advanced)' },
  { value: 'neet', label: 'NEET (UG)' },
  { value: 'ssc_cgl', label: 'SSC CGL' },
  { value: 'ssc_chsl', label: 'SSC CHSL' },
  { value: 'ssc_mts', label: 'SSC MTS' },
  { value: 'cbse_5th', label: 'CBSE 5th Grade' },
  { value: 'cbse_6th', label: 'CBSE 6th Grade' },
  { value: 'cbse_7th', label: 'CBSE 7th Grade' },
  { value: 'cbse_8th', label: 'CBSE 8th Grade' },
  { value: 'cbse_9th', label: 'CBSE 9th Grade' },
  { value: 'cbse_10th', label: 'CBSE 10th Grade' },
  { value: 'cbse_11th', label: 'CBSE 11th Grade' },
  { value: 'cbse_12th', label: 'CBSE 12th Grade' },
  { value: 'upsc', label: 'UPSC (Civil Services)' },
  { value: 'mpsc', label: 'MPSC' },
  { value: 'gate', label: 'GATE' },
  { value: 'cat', label: 'CAT' },
  { value: 'eng_comp_sci', label: 'Engineering - Computer Science' },
  { value: 'eng_electronics_telecom', label: 'Engineering - Electronics & Telecom' },
  { value: 'eng_aids', label: 'Engineering - AI & Data Science' },
  { value: 'eng_electrical', label: 'Engineering - Electrical' },
  { value: 'eng_mechanical', label: 'Engineering - Mechanical' },
  { value: 'eng_civil', label: 'Engineering - Civil' },
  { value: 'other', label: 'Other Competitive Exams' },
];

export const SUBJECTS_BY_EXAM: Record<string, Subject[]> = {
  jee: [
    { value: 'physics', label: 'Physics' },
    { value: 'chemistry', label: 'Chemistry' },
    { value: 'mathematics', label: 'Mathematics' },
  ],
  neet: [
    { value: 'physics', label: 'Physics' },
    { value: 'chemistry', label: 'Chemistry' },
    { value: 'biology', label: 'Biology (Botany & Zoology)' },
  ],
  ssc_cgl: [
    { value: 'quantitative_aptitude', label: 'Quantitative Aptitude' },
    { value: 'reasoning', label: 'General Intelligence & Reasoning' },
    { value: 'english', label: 'English Language' },
    { value: 'general_awareness', label: 'General Awareness' },
  ],
  ssc_chsl: [
    { value: 'quantitative_aptitude', label: 'Quantitative Aptitude' },
    { value: 'reasoning', label: 'General Intelligence & Reasoning' },
    { value: 'english', label: 'English Language' },
    { value: 'general_awareness', label: 'General Awareness' },
  ],
  ssc_mts: [
    { value: 'numerical_mathematical_ability', label: 'Numerical & Mathematical Ability' },
    { value: 'reasoning_problem_solving', label: 'Reasoning Ability & Problem Solving' },
    { value: 'english', label: 'English Language & Comprehension' },
    { value: 'general_awareness', label: 'General Awareness' },
  ],
  cbse_5th: [
    { value: 'mathematics', label: 'Mathematics' },
    { value: 'environmental_studies', label: 'Environmental Studies (EVS)' },
    { value: 'english', label: 'English' },
    { value: 'hindi', label: 'Hindi' },
  ],
  cbse_6th: [
    { value: 'mathematics', label: 'Mathematics' },
    { value: 'science', label: 'Science' },
    { value: 'social_science', label: 'Social Science' },
    { value: 'english', label: 'English' },
    { value: 'hindi', label: 'Hindi' },
    { value: 'sanskrit', label: 'Sanskrit' },
  ],
  cbse_7th: [
    { value: 'mathematics', label: 'Mathematics' },
    { value: 'science', label: 'Science' },
    { value: 'social_science', label: 'Social Science' },
    { value: 'english', label: 'English' },
    { value: 'hindi', label: 'Hindi' },
    { value: 'sanskrit', label: 'Sanskrit' },
  ],
  cbse_8th: [
    { value: 'mathematics', label: 'Mathematics' },
    { value: 'science', label: 'Science' },
    { value: 'social_science', label: 'Social Science' },
    { value: 'english', label: 'English' },
    { value: 'hindi', label: 'Hindi' },
    { value: 'sanskrit', label: 'Sanskrit' },
  ],
  cbse_9th: [
    { value: 'mathematics', label: 'Mathematics' },
    { value: 'science', label: 'Science (Physics, Chemistry, Biology)' },
    { value: 'social_science', label: 'Social Science (History, Geography, Civics, Economics)' },
    { value: 'english', label: 'English Language & Literature' },
    { value: 'hindi_course_a', label: 'Hindi Course A' },
    { value: 'hindi_course_b', label: 'Hindi Course B' },
  ],
  cbse_10th: [
    { value: 'mathematics', label: 'Mathematics' },
    { value: 'science', label: 'Science (Physics, Chemistry, Biology)' },
    { value: 'social_science', label: 'Social Science (History, Geography, Civics, Economics)' },
    { value: 'english', label: 'English Language & Literature' },
    { value: 'hindi_course_a', label: 'Hindi Course A' },
    { value: 'hindi_course_b', label: 'Hindi Course B' },
  ],
   cbse_11th: [
    { value: 'physics', label: 'Physics' },
    { value: 'chemistry', label: 'Chemistry' },
    { value: 'mathematics', label: 'Mathematics' },
    { value: 'biology', label: 'Biology' },
    { value: 'accountancy', label: 'Accountancy' },
    { value: 'business_studies', label: 'Business Studies' },
    { value: 'economics', label: 'Economics' },
    { value: 'english_core', label: 'English Core' },
    { value: 'computer_science', label: 'Computer Science' },
    { value: 'informatics_practices', label: 'Informatics Practices' },
    { value: 'history', label: 'History' },
    { value: 'political_science', label: 'Political Science' },
    { value: 'geography', label: 'Geography' },
    { value: 'psychology', label: 'Psychology' },
    { value: 'sociology', label: 'Sociology' },
  ],
   cbse_12th: [
    { value: 'physics', label: 'Physics' },
    { value: 'chemistry', label: 'Chemistry' },
    { value: 'mathematics', label: 'Mathematics' },
    { value: 'biology', label: 'Biology' },
    { value: 'accountancy', label: 'Accountancy' },
    { value: 'business_studies', label: 'Business Studies' },
    { value: 'economics', label: 'Economics' },
    { value: 'english_core', label: 'English Core' },
    { value: 'computer_science', label: 'Computer Science' },
    { value: 'informatics_practices', label: 'Informatics Practices' },
    { value: 'history', label: 'History' },
    { value: 'political_science', label: 'Political Science' },
    { value: 'geography', label: 'Geography' },
    { value: 'psychology', label: 'Psychology' },
    { value: 'sociology', label: 'Sociology' },
  ],
  upsc: [
    { value: 'history', label: 'History of India and Indian National Movement' },
    { value: 'geography', label: 'Indian and World Geography' },
    { value: 'polity', label: 'Indian Polity and Governance' },
    { value: 'economics', label: 'Economic and Social Development' },
    { value: 'environment', label: 'Environmental Ecology, Bio-diversity and Climate Change' },
    { value: 'general_science', label: 'General Science' },
    { value: 'current_events', label: 'Current events of national and international importance' },
    { value: 'csat', label: 'CSAT (Aptitude)'},
  ],
  mpsc: [
    { value: 'marathi', label: 'Marathi' },
    { value: 'english', label: 'English' },
    { value: 'general_studies', label: 'General Studies' },
    { value: 'csat_mpsc', label: 'CSAT (MPSC)'},
  ],
  gate: [
    { value: 'general_aptitude', label: 'General Aptitude' },
    { value: 'engineering_mathematics', label: 'Engineering Mathematics' },
    { value: 'cse_gate', label: 'Computer Science and IT' },
    { value: 'ece_gate', label: 'Electronics and Communication' },
    { value: 'ee_gate', label: 'Electrical Engineering' },
    { value: 'me_gate', label: 'Mechanical Engineering' },
    { value: 'ce_gate', label: 'Civil Engineering' },
    // Add other GATE branches if needed
  ],
  cat: [
    { value: 'varc', label: 'Verbal Ability & Reading Comprehension (VARC)' },
    { value: 'dilr', label: 'Data Interpretation & Logical Reasoning (DILR)' },
    { value: 'qa_cat', label: 'Quantitative Ability (QA)' },
  ],
  eng_comp_sci: [
    { value: 'data_structures_algorithms', label: 'Data Structures & Algorithms' },
    { value: 'discrete_mathematics', label: 'Discrete Mathematics' },
    { value: 'operating_systems', label: 'Operating Systems' },
    { value: 'computer_networks', label: 'Computer Networks' },
    { value: 'dbms', label: 'Database Management Systems' },
    { value: 'toc_cd', label: 'Theory of Computation & Compiler Design' },
  ],
  eng_electronics_telecom: [
    { value: 'electronic_devices_circuits', label: 'Electronic Devices & Circuits' },
    { value: 'digital_electronics', label: 'Digital Electronics' },
    { value: 'signals_systems', label: 'Signals & Systems' },
    { value: 'communication_systems', label: 'Communication Systems' },
    { value: 'emft', label: 'Electromagnetic Field Theory' },
  ],
  eng_aids: [
    { value: 'programming_python_r', label: 'Programming (Python/R)' },
    { value: 'machine_learning', label: 'Machine Learning' },
    { value: 'deep_learning', label: 'Deep Learning' },
    { value: 'big_data_analytics', label: 'Big Data Analytics' },
    { value: 'statistics_probability', label: 'Statistics & Probability' },
  ],
  eng_electrical: [
    { value: 'electric_circuits', label: 'Electric Circuits' },
    { value: 'electrical_machines', label: 'Electrical Machines' },
    { value: 'power_systems', label: 'Power Systems' },
    { value: 'control_systems', label: 'Control Systems' },
    { value: 'power_electronics', label: 'Power Electronics' },
  ],
  eng_mechanical: [
    { value: 'thermodynamics', label: 'Thermodynamics' },
    { value: 'fluid_mechanics', label: 'Fluid Mechanics' },
    { value: 'strength_materials', label: 'Strength of Materials' },
    { value: 'theory_machines', label: 'Theory of Machines' },
    { value: 'manufacturing_science', label: 'Manufacturing Science' },
  ],
  eng_civil: [
    { value: 'structural_analysis', label: 'Structural Analysis' },
    { value: 'geotechnical_engineering', label: 'Geotechnical Engineering' },
    { value: 'transportation_engineering', label: 'Transportation Engineering' },
    { value: 'environmental_engineering', label: 'Environmental Engineering' },
    { value: 'fluid_mechanics_hydraulics', label: 'Fluid Mechanics & Hydraulics' },
  ],
  other: [
    { value: 'general_studies', label: 'General Studies' },
    { value: 'aptitude', label: 'Aptitude' },
    { value: 'reasoning', label: 'Reasoning' },
    { value: 'english', label: 'English' },
  ],
};

export const ALL_SUBJECTS_OPTION: Subject = { value: 'all', label: 'All Subjects' };

export const QUIZ_DIFFICULTY_LEVELS: QuizDifficultyLevel[] = [
  { value: 'easy', label: 'Easy' },
  { value: 'medium', label: 'Medium' },
  { value: 'high', label: 'High' },
  { value: 'expert', label: 'Expert' },
];
